from django.urls import path
from . import views
from . import chat_views
from . import claim_views
from .assistance import assistant_reply, request_answer, assistance_requests

urlpatterns = [
    path('assistance/reply/', assistant_reply, name='assistant_reply'),
    path('assistance/request/', request_answer, name='request_answer'),
    path('assistance/requests/', assistance_requests, name='assistance_requests'),
    path('my-claims/', claim_views.my_claims, name='my_claims'),
    path('claims/<int:claim_id>/appeal/', claim_views.appeal_claim, name='appeal_claim'),
    path('claims/<int:claim_id>/end/', claim_views.end_claim, name='end_claim'),
    path('claims/<int:claim_id>/resend-code/', claim_views.resend_claim_code, name='resend_claim_code'),
    path('notifications/', claim_views.notifications, name='notifications'),
    path('notifications/count/', claim_views.notification_count, name='notification_count'),
    path('notifications/<int:event_id>/open/', claim_views.open_notification, name='open_notification'),
    path('notifications/<int:event_id>/read/', claim_views.mark_notification_read, name='mark_notification_read'),
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('report/', views.report_item, name='report_item'),
    path('items/', views.item_list, name='item_list'),
    path('items/<int:item_id>/', views.item_detail, name='item_detail'),
    path('items/<int:item_id>/contact/', views.contact_item_owner, name='contact_item_owner'),
    path('items/<int:item_id>/claim/', views.submit_claim, name='submit_claim'),
    path('items/<int:item_id>/claims/', views.manage_claims, name='manage_claims'),
    path('claims/<int:claim_id>/review/', views.review_claim, name='review_claim'),
    path('items/<int:item_id>/mark_returned/', views.mark_item_returned, name='mark_item_returned'),
    path('inbox/', chat_views.inbox, name='inbox'),
    path('items/<int:item_id>/message/<int:recipient_id>/', chat_views.send_message, name='send_message'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path('items/<int:item_id>/return_confirmation/', views.return_confirmation, name='return_confirmation'),
    path('profile/remove-picture/', views.remove_profile_picture, name='remove_profile_picture'),
    path('review/<int:user_id>/', views.submit_review, name='submit_review'),
    path('items/<int:item_id>/edit/', views.edit_item_fields, name='edit_item_fields'),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    path('profile/upload-picture/', views.upload_profile_picture, name='upload_profile_picture'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('my-recovered-items/', views.my_recovered_items, name='my_recovered_items'),
    path('my-returned-items/', views.my_returned_items, name='my_returned_items'),
    path('items/<int:item_id>/rate/', views.rate_finder, name='rate_finder'),
    path('statistics/returns/', views.returns_statistics, name='returns_statistics'),
    path('export/recovered-items/pdf/', views.export_recovered_items_pdf, name='export_recovered_items_pdf'),
    path('clear-conversation/', chat_views.conversation_action, name='clear_conversation'),
    path('message/send/', chat_views.send_chat_message, name='send_chat_message'),
    path('message/edit/', chat_views.edit_message, name='edit_message'),
    path('message/delete/', chat_views.delete_message, name='delete_message'),
    path('conversation/read/', chat_views.mark_read, name='mark_conversation_read'),
    path('conversation/sync/', chat_views.sync_conversation, name='sync_conversation'),
    path('conversation/typing/', chat_views.typing_status, name='typing_status'),
]
