# Generated by Django 5.0.6 on 2025-09-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_confirmed', models.BooleanField(default=False)),
                ('owner_confirmed', models.BooleanField(default=False)),
                ('finder_photo', models.ImageField(blank=True, null=True, upload_to='return_evidence/')),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='return_evidence/')),
                ('finder_signature', models.TextField(blank=True, null=True)),
                ('owner_signature', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_confirmation', to='FindIt.item')),
            ],
        ),
    ]
