# Generated by Django 5.1.4 on 2025-08-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
