# Generated by Django 5.0.6 on 2025-10-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0004_message_image_alter_message_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovered_date', models.DateTimeField(auto_now_add=True)),
                ('original_report_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from owner to finder (1-5 stars)', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback from owner about the return experience')),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovered_record', to='FindIt.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovered_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recovered_date'],
            },
        ),
    ]
