# Generated by Django 5.0.6 on 2025-10-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0005_recovereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reputation_score',
            field=models.FloatField(default=0.0, help_text='Average rating score'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_ratings',
            field=models.IntegerField(default=0, help_text='Total ratings received'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_returns',
            field=models.IntegerField(default=0, help_text='Total items returned to owners'),
        ),
    ]
