# Generated by Django 5.1.4 on 2025-09-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0006_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_links',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
