# Generated by Django 5.1.4 on 2025-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0007_userprofile_address_userprofile_bio_and_more'),
    ]

    operations = []
