# Generated by Django 5.2.14 on 2026-05-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0008_alter_item_photo_alter_message_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='library',
        ),
    ]
