# Generated by Django 5.2.14 on 2026-05-13 21:02

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0010_message_deleted_at_message_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnconfirmation',
            name='finder_confirmed',
        ),
        migrations.RemoveField(
            model_name='returnconfirmation',
            name='finder_photo',
        ),
        migrations.RemoveField(
            model_name='returnconfirmation',
            name='finder_signature',
        ),
        migrations.RemoveField(
            model_name='returnconfirmation',
            name='owner_confirmed',
        ),
        migrations.RemoveField(
            model_name='returnconfirmation',
            name='owner_photo',
        ),
        migrations.RemoveField(
            model_name='returnconfirmation',
            name='owner_signature',
        ),
        migrations.AddField(
            model_name='item',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='verification_status',
            field=models.CharField(choices=[('FOUND', 'Found'), ('CLAIMED', 'Claimed'), ('VERIFIED', 'Verified'), ('RETURNED', 'Returned')], default='FOUND', max_length=20),
        ),
        migrations.AddField(
            model_name='returnconfirmation',
            name='claimant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimant_return_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnconfirmation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_return_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnconfirmation',
            name='entered_claimant_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='returnconfirmation',
            name='finder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finder_return_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnconfirmation',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnconfirmation',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='returnconfirmation',
            name='confirmed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='returnconfirmation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_confirmations', to='FindIt.item'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_text', models.TextField()),
                ('proof_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code_hash', models.CharField(blank=True, max_length=128)),
                ('verification_code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code_used_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('claim_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='FindIt.item')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_item_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='returnconfirmation',
            name='claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_confirmation', to='FindIt.claim'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('item',), name='unique_approved_claim_per_item'),
        ),
    ]
