# Generated by Django 5.2.14 on 2026-05-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0011_remove_returnconfirmation_finder_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnconfirmation',
            name='confirmed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
