# Generated by Django 5.2.14 on 2026-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindIt', '0013_alter_claim_status_claimevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(default='Getting started', max_length=100)),
                ('keywords', models.TextField(help_text='Comma-separated words or phrases that match this topic.')),
                ('response', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Assistance FAQ',
                'ordering': ['-priority', 'title'],
            },
        ),
    ]
